<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>id</string>
   </array>
  <key>name</key>
  <string>swipc</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.swipc</string>
  <key>uuid</key>
  <string>8FCAFD65-DF0B-4362-A93E-68516666A1D0</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(type)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(interface)(\s+)([a-zA-Z0-9\x{003a}_]+)(\s*)(is)?([\x{0040}a-zA-Z0-9-\x{003a}_\x{0020}\x{002c}]+)?(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.swipc</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.swipc</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.swipc</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.swipc</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.swipc</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>variable.other.swipc</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(interface|type)</string>
          <key>name</key>
          <string>keyword.swipc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#decorator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.swipc</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.swipc</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.swipc</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.swipc</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>text.swipc</string>
        </dict>
       </array>
    </dict>
    <key>arguments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#typenamepair</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9\x{003a}_]+)</string>
          <key>name</key>
          <string>entity.name.type.swipc</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.swipc</string>
        </dict>
       </array>
    </dict>
    <key>decorator</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(@[a-z]+)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.decorator.swipc</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.swipc</string>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(@[a-z]+)</string>
          <key>name</key>
          <string>entity.name.function.decorator.swipc</string>
        </dict>
       </array>
    </dict>
    <key>decorator__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>interface</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#interface__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#decorator</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#interface__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(-&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#interface__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.swipc</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9_]+)</string>
          <key>name</key>
          <string>entity.name.function.swipc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.swipc</string>
        </dict>
       </array>
    </dict>
    <key>interface__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.swipc</string>
        </dict>
       </array>
    </dict>
    <key>interface__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#arguments</string>
        </dict>
       </array>
    </dict>
    <key>interface__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#arguments</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#struct</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9\x{003a}_]+)</string>
          <key>name</key>
          <string>entity.name.type.swipc</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#interface</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.swipc</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.swipc</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.swipc</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.swipc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(0x[0-9a-fA-F]+)|\d+)</string>
          <key>name</key>
          <string>constant.numeric.swipc</string>
        </dict>
       </array>
    </dict>
    <key>struct</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(struct)</string>
          <key>name</key>
          <string>keyword.swipc</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#struct__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>struct__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.swipc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#typenamepair</string>
        </dict>
       </array>
    </dict>
    <key>typenamepair</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([a-zA-Z0-9\x{003a}_]+)(&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.swipc</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#typenamepair__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&gt;)((\s*[a-zA-Z0-9_]+)?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swipc</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.swipc</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.swipc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9\x{003a}_]+)(\s*([a-zA-Z_0-9]+)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.swipc</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.swipc</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.swipc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>typenamepair__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.swipc</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z0-9_\x{003a}]+)</string>
          <key>name</key>
          <string>keyword.swipc</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
